name: Go Build

on:
  push:
    tags:
      - 'v*.*.*'  # Only run when pushing a version tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.4'

    - name: Disable Go modules (GO111MODULE=off)
      run: echo "GO111MODULE=off" >> $GITHUB_ENV  # Set GO111MODULE=off for all steps

    - name: Run build for Linux
      run: go build -o poker-calculator-linux poker-calculator.go

    - name: Run build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o poker-calculator-windows poker-calculator.go

    - name: Run build for Mac Intel
      run: GOOS=darwin GOARCH=amd64 go build -o poker-calculator-macos-intel poker-calculator.go

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          poker-calculator.exe
          poker-calculator
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
